In [102]:
# import numpy as np
# import cv2
# from mss import mss
# from PIL import Image
# import pyautogui as pg
# import pydirectinput
# pyautogui.FAILSAFE = False
# import time
# import math

# def target(source_img, target_filename):
#     target_img = cv2.imread(target_filename, cv2.IMREAD_UNCHANGED)
#     result = cv2.matchTemplate(source_img, target_img, cv2.TM_CCOEFF_NORMED)
#     min_val, max_val, mix_loc, max_loc = cv2.minMaxLoc(result)
#     w = target_img.shape[1]
#     h = target_img.shape[0]

#     threshold = .88

#     yloc, xloc = np.where(result >= threshold)
#     if(len(xloc) == 0):
#         print('cannot detech')
#         return 0, 0, 0, 0
    
#     return xloc[0], yloc[0], w, h

# def main():
#     bounding_box = {'left': 0, 'top': 0, 'width': 1980, 'height': 1080}

#     sct = mss()

#     target_img = cv2.imread('target.png', cv2.IMREAD_UNCHANGED)

#     final_rectangles = []

#     # while True:
#     screen = sct.grab(bounding_box)
#     source_img = np.array(screen)
#     result = cv2.matchTemplate(source_img, target_img, cv2.TM_CCOEFF_NORMED)
#     min_val, max_val, mix_loc, max_loc = cv2.minMaxLoc(result)
#     w = target_img.shape[1]
#     h = target_img.shape[0]

#     threshold = .98

#     yloc, xloc = np.where(result >= threshold)
#     if(len(xloc) == 0):
#         return

#     #     rectangles = []
#     #     for (x,y) in zip(xloc, yloc):
#     #         rectangles.append([int(x), int(y), int(w), int(h)])
#     #         rectangles.append([int(x), int(y), int(w), int(h)])

#     #     rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
#     # #     if np.array_equal(final_rectangles, rectangles, equal_nan=True):
#     # #         final_rectangles = rectangles
#     # #         print(len(rectangles))

#     #     for (x,y, w, h) in rectangles:
#     #         cv2.rectangle(source_img, (x,y), (x+w, y+h), (0,255,255), 2)
#     #     cv2.imshow('screen', np.array(source_img))

#     #     print((rectangles[0][0]+rectangles[0][2]/2),(rectangles[0][1]+rectangles[0][3]/2))
#     ## pg.moveTo((rectangles[0][0]+rectangles[0][2]/2),(rectangles[0][1]+rectangles[0][3]/2), 4)

#     x, y = math.floor(xloc[0]+w/2),math.floor(yloc[0]+h/2)
#     # pg.moveTo(0,0,1)
#     # time.sleep(3)

#     pydirectinput.moveTo(x, y, 1)
#     pg.rightClick(x, y)
#     pydirectinput.moveTo(x+20, y+50, 1)
#     pg.click(x+20, y+50)
#     time.sleep(1)

#     # zhu he
#     x,y,_,_ = target(source_img, 'target2.png')
#     if(x == 0) & (y == 0):
#         return
#     pydirectinput.moveTo(x+10, y+120, 1)
#     pg.click(x+10, y+120)
#     pydirectinput.moveTo(x+140, y+330, 1)    
#     pg.click(x+140, y+330, 1)

#     # pg.click((rectangles[0][0]+rectangles[0][2]/2),(rectangles[0][1]+rectangles[0][3]/2),button='right')
#     #     cv2.waitKey(0)

#     #     if (cv2.waitKey(1) & 0xFF) == ord('q'):
#     #         cv2.destroyAllWindows()
#     #         break
    
# main()

In [60]:
### import numpy as np
import cv2
from mss import mss
sct = mss()
from PIL import Image
import pyautogui as pg
import pydirectinput
import time
import math
import os.path


def target(target_filename):
    bounding_box = {'left': 0, 'top': 0, 'width': 1980, 'height': 1080}
    screen = sct.grab(bounding_box)
    source_img = np.array(screen)
    target_img = cv2.imread(target_filename, cv2.IMREAD_UNCHANGED)
    result = cv2.matchTemplate(source_img, target_img, cv2.TM_CCOEFF_NORMED)
    min_val, max_val, mix_loc, max_loc = cv2.minMaxLoc(result)
    w = target_img.shape[1]
    h = target_img.shape[0]

    threshold = .88

    yloc, xloc = np.where(result >= threshold)
    if(len(xloc) == 0):
        print('cannot detech')
        time.sleep(0.1)
        return target(target_filename)
    
    return xloc[0], yloc[0], w, h

def zhuhe():
    x,y,_,_ = target('zhuhe.png')
    if(x == 0) & (y == 0):
        return
    pydirectinput.moveTo(x+10, y+120)
    pg.click(x+10, y+120)
    pydirectinput.moveTo(x+140, y+330)    
    pg.click(x+140, y+330)

    time.sleep(0.1)
    
def rearrange():
    x,y,_,_ = target('rearrange.png')
    if(x == 0) & (y == 0):
        return
    pydirectinput.moveTo(x+10, y+10)
    pg.click(x+10, y+10)
    time.sleep(0.1)

def get_page():
    x,y,w,h = target('bag_page.png')
    if(x == 0) & (y == 0):
        return
    return x,y,w,h
    
def go_to_page(current_page, x, y, w, h):
    if (current_page > 4):
        return
    pydirectinput.moveTo(int(x+w/2), int(y+h/4*current_page-15))
    pg.click(int(x+w/2), int(y+h/4*current_page-15))
    print('Clicked page {0}'.format(current_page))
    time.sleep(0.1)
    
def search_and_build_item(filename):
    is_file_exists = os.path.exists(filename)
    if (is_file_exists != True):
        return
    
    bounding_box = {'left': 0, 'top': 0, 'width': 1980, 'height': 1080}
    target_img = cv2.imread(filename, cv2.IMREAD_UNCHANGED)
    count = 0
    while True:
        screen = sct.grab(bounding_box)
        source_img = np.array(screen)
        result = cv2.matchTemplate(source_img, target_img, cv2.TM_CCOEFF_NORMED)
        min_val, max_val, mix_loc, max_loc = cv2.minMaxLoc(result)
        w = target_img.shape[1]
        h = target_img.shape[0]

        threshold = .98

        yloc, xloc = np.where(result >= threshold)
        if(len(xloc) == 0):
            break

        x, y = math.floor(xloc[0]+w/2),math.floor(yloc[0]+h/2)

        pydirectinput.moveTo(x, y)
        pg.rightClick(x, y)
        pydirectinput.moveTo(x+20, y+50)
        pg.click(x+20, y+50)
        time.sleep(0.1)

        # zhu he
        zhuhe()
        count += 1
    return count
        
def refill(count):
    x,y,_,_ = target('refill_1.png')
    if(x == 0) & (y == 0):
        return
    pydirectinput.moveTo(x+10, y+10)
    pg.click(x+10, y+10)
    time.sleep(0.1)
    
    x,y,_,_ = target('refill_2.png')
    if(x == 0) & (y == 0):
        return
    pydirectinput.moveTo(x+10, y+10)
    pg.rightClick(x+10, y+10)
    time.sleep(0.1)
    
    x,y,_,_ = target('refill_3.png')
    if(x == 0) & (y == 0):
        return
    pydirectinput.moveTo(x+10, y+10)
    pg.rightClick(x+10, y+10)
    time.sleep(0.1)
    
    x,y,_,_ = target('refill_4.png')
    if(x == 0) & (y == 0):
        return
    pydirectinput.moveTo(x+10, y+10)
    pg.rightClick(x+10, y+10)
    time.sleep(0.1)
    
    x,y,w,_ = target('refill_5.png')
    if(x == 0) & (y == 0):
        return
    pydirectinput.moveTo(x+w-10, y+10)
    pg.click(x+w-10, y+10)
    time.sleep(0.1)
    
    for i in range(count):
        pydirectinput.typewrite('3')
        time.sleep(0.1)
    time.sleep(0.1)

def main():
    rearrange()

    page_x,page_y,page_w,page_h = get_page()
    
    count = 0
    for current_page in range(4):
        go_to_page(current_page+1, page_x,page_y,page_w,page_h)
        for level in range(4):
            for item in range(5):
                filename = 'item_{0}_{1}.png'.format(item, level)
                count += search_and_build_item(filename)
    print('done')
    print(count)

    refill(count)
    
main()

Clicked page 1
Clicked page 2
Clicked page 3
Clicked page 4
done
42


In [11]:
# import numpy as np
# import cv2
# from PIL import ImageGrab as ig
# import time

# last_time = time.time()
# while(True):
#     screen = ig.grab(bbox=(0,0,1980,1080))
#     print('Loop took {} seconds',format(time.time()-last_time))
#     print(np.array(screen))
#     cv2.imshow("test", np.array(screen))
#     last_time = time.time()
#     if cv2.waitKey(25) & 0xFF == ord('q'):
#         cv2.destroyAllWindows()
#         break

Loop took {} seconds 0.14707684516906738
[[[ 43 125 166]
  [ 43 125 166]
  [ 43 125 166]
  ...
  [ 43 104 155]
  [ 43 104 155]
  [ 43 104 155]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 41  43  28]
  [ 83  86  58]
  [ 88  91  64]
  ...
  [ 66  67  62]
  [ 66  67  62]
  [ 66  67  62]]

 [[ 40  42  28]
  [ 81  84  56]
  [ 83  86  59]
  ...
  [ 67  69  64]
  [ 67  69  64]
  [ 67  69  64]]

 [[ 44  45  31]
  [ 86  90  62]
  [ 84  87  59]
  ...
  [ 69  71  66]
  [ 69  71  66]
  [ 69  71  66]]]
Loop took {} seconds 0.15345120429992676
[[[ 43 125 166]
  [ 43 125 166]
  [ 43 125 166]
  ...
  [ 43 104 155]
  [ 43 104 155]
  [ 43 104 155]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255

Loop took {} seconds 0.14000463485717773
[[[ 43 125 166]
  [ 43 125 166]
  [ 43 125 166]
  ...
  [ 43 104 155]
  [ 43 104 155]
  [ 43 104 155]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 41  43  28]
  [ 83  86  58]
  [ 88  91  64]
  ...
  [ 59  61  51]
  [ 59  61  51]
  [ 59  61  52]]

 [[ 40  42  28]
  [ 81  84  56]
  [ 83  86  59]
  ...
  [ 57  60  52]
  [ 58  61  53]
  [ 59  62  54]]

 [[ 44  45  31]
  [ 86  90  62]
  [ 84  87  59]
  ...
  [ 57  61  53]
  [ 58  62  54]
  [ 59  63  55]]]
Loop took {} seconds 0.15230822563171387
[[[ 43 125 166]
  [ 43 125 166]
  [ 43 125 166]
  ...
  [ 43 104 155]
  [ 43 104 155]
  [ 43 104 155]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255

In [10]:
# import numpy as np
# import cv2
# from PIL import ImageGrab as ig
# import time

# last_time = time.time()
# target_img = cv2.imread('target.png', cv2.IMREAD_UNCHANGED)

# while(True):
#     screen = ig.grab(bbox=(0,0,1980,1080))
#     source_img = np.array(screen)
#     result = cv2.matchTemplate(source_img, target_img, cv2.TM_CCOEFF_NORMED)
#     min_val, max_val, mix_loc, max_loc = cv2.minMaxLoc(result)
#     w = target_img.shape[1]
#     h = target_img.shape[0]
    
#     # cv2.rectangle(source_img, max_loc, (max_loc[0] + w, max_loc[1] + h), (0,255,255),2)
#     threshold = .68
    
#     yloc, xloc = np.where(result >= threshold)
    
#     #for (x,y) in zip(xloc, yloc):
#     #    cv2.rectangle(source_img, (x,y), (x+w, y+h), (0,255,255), 2)
    
#     rectangles = []
#     for (x,y) in zip(xloc, yloc):
#         rectangles.append([int(x), int(y), int(w), int(h)])
#         rectangles.append([int(x), int(y), int(w), int(h)])

#     rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
    
#     for (x,y, w, h) in rectangles:
#         cv2.rectangle(source_img, (x,y), (x+w, y+h), (0,255,255), 2)
        
#     cv2.imshow("test", source_img)
#     last_time = time.time()
#     if cv2.waitKey(25) & 0xFF == ord('q'):
#         cv2.destroyAllWindows()
#         break

[[[ 70  58  44 255]
  [ 14  13  11 255]
  [ 14  13  11 255]
  ...
  [ 16  15  13 255]
  [ 15  15  13 255]
  [ 14  14  12 255]]

 [[ 68  56  42 255]
  [ 14  13  12 255]
  [ 15  14  13 255]
  ...
  [ 21  20  17 255]
  [ 18  17  15 255]
  [ 15  15  13 255]]

 [[ 66  54  40 255]
  [ 15  14  13 255]
  [ 17  16  15 255]
  ...
  [ 42  41  38 255]
  [ 30  29  27 255]
  [ 18  17  15 255]]

 ...

 [[ 33  24  16 255]
  [ 14  13  11 255]
  [ 15  14  12 255]
  ...
  [ 20  19  16 255]
  [ 17  16  14 255]
  [ 15  14  12 255]]

 [[ 33  24  16 255]
  [ 14  13  11 255]
  [ 14  13  11 255]
  ...
  [ 16  14  13 255]
  [ 15  14  12 255]
  [ 14  13  11 255]]

 [[ 37  26  16 255]
  [ 32  24  16 255]
  [ 32  24  16 255]
  ...
  [ 33  24  16 255]
  [ 32  24  16 255]
  [ 32  24  16 255]]]
